CREATE TABLE ecommerce_data (
    order_id INT PRIMARY KEY,
    customer_id INT,
    customer_name VARCHAR(100),
    gender VARCHAR(10),
    age INT,
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    product_id INT,
    product_name VARCHAR(100),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    quantity INT,
    unit_price DECIMAL(10,2),
    discount DECIMAL(5,2),
    total_amount DECIMAL(10,2),
    payment_mode VARCHAR(20),
    order_date DATE,
    delivery_status VARCHAR(20),
    rating DECIMAL(2,1)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/ecommerce_data.csv'
INTO TABLE ecommerce_data
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

# View all records
SELECT * FROM ecommerce_data;

# Show total number of records
SELECT COUNT(*) AS total_orders FROM ecommerce_data;

# Display unique product categories
SELECT DISTINCT category FROM ecommerce_data;

# Retrieve orders where payment mode is 'UPI'
SELECT * FROM ecommerce_data
WHERE payment_mode = 'UPI';

# Get orders placed in 2024 only
SELECT * FROM ecommerce_data
WHERE YEAR(order_date) = 2024;

# Find top 10 highest total amount orders
SELECT order_id, customer_name, total_amount
FROM ecommerce_data
ORDER BY total_amount DESC
LIMIT 10;

# Calculate total revenue generated
SELECT SUM(total_amount) AS total_revenue
FROM ecommerce_data;

# Find average order value (AOV)
SELECT AVG(total_amount) AS avg_order_value
FROM ecommerce_data;

# Count of orders per payment mode
SELECT payment_mode, COUNT(*) AS total_orders
FROM ecommerce_data
GROUP BY payment_mode
ORDER BY total_orders DESC;

# Average rating by category
SELECT category, ROUND(AVG(rating),2) AS avg_rating
FROM ecommerce_data
GROUP BY category;

# Total quantity sold by each sub-category
SELECT sub_category, SUM(quantity) AS total_quantity
FROM ecommerce_data
GROUP BY sub_category
ORDER BY total_quantity DESC;

# Revenue generated by each state
SELECT state, ROUND(SUM(total_amount),2) AS total_revenue
FROM ecommerce_data
GROUP BY state
ORDER BY total_revenue DESC;

# Top 5 cities with highest total revenue
SELECT city, SUM(total_amount) AS city_revenue
FROM ecommerce_data
GROUP BY city
ORDER BY city_revenue DESC
LIMIT 5;

# Find orders that were returned or cancelled
SELECT * FROM ecommerce_data
WHERE delivery_status IN ('Returned', 'Cancelled');

# Get customers who gave a rating below 2
SELECT customer_name, rating, total_amount
FROM ecommerce_data
WHERE rating < 2
ORDER BY rating ASC;

# Calculate average discount by category
SELECT category, ROUND(AVG(discount),2) AS avg_discount
FROM ecommerce_data
GROUP BY category
ORDER BY avg_discount DESC;

# Get total sales by gender
SELECT gender, ROUND(SUM(total_amount),2) AS total_sales
FROM ecommerce_data
GROUP BY gender;

# Highest rated products (avg rating per product)
SELECT product_name, ROUND(AVG(rating),2) AS avg_rating
FROM ecommerce_data
GROUP BY product_name
ORDER BY avg_rating DESC
LIMIT 10;

# Monthly sales trend (year & month)
SELECT YEAR(order_date) AS year, MONTH(order_date) AS month,
       ROUND(SUM(total_amount),2) AS monthly_sales
FROM ecommerce_data
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY year, month;

# Total orders, revenue, and average rating per category
SELECT category,
       COUNT(*) AS total_orders,
       ROUND(SUM(total_amount),2) AS total_revenue,
       ROUND(AVG(rating),2) AS avg_rating
FROM ecommerce_data
GROUP BY category
ORDER BY total_revenue DESC;



